[project]
name = "adveritas-backend"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
  "fastapi==0.115.0",
  "uvicorn[standard]==0.30.6",
  "pydantic==2.9.2",
  "SQLAlchemy==2.0.35",
  "psycopg[binary]==3.2.3",
  "alembic==1.13.2",
  "redis==5.0.8",
  "celery==5.4.0",
  "boto3==1.35.36",
  "python-multipart==0.0.12",
  "httpx==0.27.2",
  "fastapi-cors==0.0.6",
  "pgvector==0.2.5",
  "faster-whisper==1.1.0",
  "nltk==3.9.1",
  "transformers==4.44.2",
  "torch==2.4.1",
  "sentence-transformers==3.1.1",
  "wikipedia==1.4.0",
  "requests==2.32.3",
  "json5==0.9.25",
]

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.uvicorn]
factory = true